---
- hosts: localhost
  gather_facts: false
  ignore_errors: true
  connection: local
  roles:
  - role: ansible_role_integration_execute
  vars:
    final_ack: false
    eiroles_enable:
      socks_tunnel_role: true
      final_ack_role: true
  tasks:
   - debug:
       msg:
          - "affected_host={{ affected_host | default('UNDEFINED') }}"
          - "sr_data={{ sr_data | default('UNDEFINED') }}"
          - "first_job_id={{ first_job_id | default('UNDEFINED') }}"

# ***** Calling common playbook  *****
- name: Calling common playbook
  hosts: "{{ hostvars['localhost']['affected_host'] }}"
  become: "{{ (ostype != 'windows') | ternary('yes', 'no') }}"
  gather_facts: false
  tasks:
    - name: Include ansible_role_integration_sra_common_playbook
      include_role:
        name: ansible_role_integration_sra_common_playbook
      when:
        - not hostvars["localhost"]["usecase_role_stat"]
        - '(hostvars[hostvars["localhost"]["affected_host"]]["host_reachable"]|default("false")) == true'
        - hostvars['localhost']['common_role_name'] | default("None") != "None"
        - hostvars['localhost']['custom_playbook'] | default(False) == False
        

- hosts: localhost
  gather_facts: false
  connection: local
  ignore_errors: true
  roles:
    - role: ansible_role_integration_execute
  vars:
    final_ack: true
 
