matchers:
# - name: hello-world
#   enabled: true
#   skip_precheck: true
#   custom_playbook: false
#   matcher_expressions:
#     - classification: ITDRESLIN037
#     - classification: ^.*ITDRESLIN037.*$ 

  - name: ansible_role_integration_db2
    enabled: true
    custom_playbook: false
    skip_precheck: false
    matcher_expressions:
      - classification: ^RAFINTEDB2$
