---
<<<<<<< HEAD
- hosts: "{{ affected_hosts }}"
  tasks:
    - name: check uptime
      command: uptime
      register: uptime_out
=======
hosts: affected_hosts
tasks:
  - name: check uptime
    command: uptime
    register: uptime_out
>>>>>>> parent of ddde439 (update uptime play)

    - debug:
        var: uptime_out.stdout_lines
