  
#- name: ansible_role_integration_preprocessor
#  src: git+https://github.kyndryl.net/IBM-GTS-JP-Shared/ansible_role_integration_preprocessor.git
#  version: master

- name: ansible_role_integration_findaffectedhost
  src: git+https://github.com/kyndryl-global-delivery/ansible_role_integration_findaffectedhost.git
  version: master
  
  
#- name: ansible_role_integration_sra_common_playbook
#  src: git+https://github.com/kyndryl-global-delivery/ansible_role_integration_sra_common_playbook.git
#  version: main
  
#- name: ansible_role_integration_sra_mapper
#  src: git+https://github.com/kyndryl-global-delivery/ansible_role_integration_sra_mapper.git
#  version: main

#- name: ansible-role-event-pre-check
#  src: git+https://github.com/kyndryl-global-delivery/ansible-role-event-pre-check.git
#  version: master  
  
#- name: ansible-role-event-socks-tunnel
#  src: git+https://github.com/kyndryl-global-delivery/ansible-role-event-socks-tunnel.git
#  version: master
  
#- name: ansible-role-event-NetcoolDummyHandler
#  src: git+https://github.com/kyndryl-global-delivery/ansible-role-event-NetcoolDummyHandler.git
#  version: master
  
#- name: ansible-role-incident-data
#  src: git+https://github.com/kyndryl-global-delivery/ansible-role-incident-data.git
#  version: master
  
#- name: ansible_role_event_validate_input
#  src: git+https://github.com/kyndryl-global-delivery/ansible_role_event_validate_input.git
#  version: master

#- name: ansible_role_integration_sra_success_testing 
#  src: git+https://github.com/kyndryl-global-delivery/ansible_role_integration_sra_success_testing.git
#  version: main
  
#- name: ansible_role_integration_sra_failure_testing
#  src: git+https://github.com/kyndryl-global-delivery/ansible_role_integration_sra_failure_testing.git
#  version: main

#- name: sra_linux_change_rights_file_dir
#  src: git+https://github.com/kyndryl-global-delivery/ansible_role_sra_linux_change_rights_file_dir.git
#  version: 1.2/main
  
#- name: sra_restart_linux
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_restart_linux_server.git
#  version: 1.2/main
#  
#- name: sra_manage_service_windows
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_manage_service_windows.git
#  version: 1.1/main
#  
#- name: sra_restart_windows
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_restart_windows_server.git
#  version: 1.1/main
#  
#- name: sra_manage_service_linux
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_manage_service_linux.git
#  version: 1.3/main
#  
#- name: sra_install_remove_linux_package
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_install_remove_linux_package.git
#  version: 1.1/main
#  
#- name: sra_config_firewall_rule_windows
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_config_firewall_rule_windows.git
#  version: 1.1/main
#  
#- name: sra_change_linux_system_configuration_value
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_change_linux_system_configuration_value.git
#  version: 1.1/main
#
#- name: ansible_role_sra_trigger_job_template
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_trigger_job_template.git
#  version: development
#
#- name: sra_manage_vm
#  src: git+https://github.kyndryl.net/Innovate/gat_ansible_role_sra_manage_vm.git
#  version: 1.1.0
#  
#- name: sra_printer_hungfix
#  src: git+https://github.kyndryl.net/EU-France-SGI/sra_printer_hungfix.git
#  version: main
#
## Middleware Usecases BEGIN
#- name: sra_mw_ux_apache_tomcat_start
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mw_ux_apache_tomcat_start.git
#  version: 1.1/main
#- name: sra_mw_ux_apache_tomcat_stop
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mw_ux_apache_tomcat_stop.git
#  version: 1.1/main
#- name: sra_mw_win_apache_tomcat_start
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mw_win_apache_tomcat_start.git
#  version: main
#- name: sra_mw_win_apache_tomcat_stop
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mw_win_apache_tomcat_stop.git
#  version: 1.1/main
#- name: sra_mw_win_apache_tomcat_remove_example
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mw_win_apache_tomcat_remove_example.git
#  version: 1.1/main
#- name: sra_mw_ux_apache_tomcat_deploy_app
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mw_ux_apache_tomcat_deploy_app.git
#  version: 1.1/main
#- name: sra_mw_win_apache_tomcat_deploy_app
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mw_win_apache_tomcat_deploy_app.git
#  version: 1.0/main
#- name: sra_mw_win_apache_tomcat_svc_start
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mw_win_apache_tomcat_svc_start.git
#  version: 1.1/main
#  
#- name: sra_mw_ux_tomcat_remove_example
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mw_ux_tomcat_remove_example.git
#  version: 1.1/main
#- name: sra_mw_win_tomcat_heap_config
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mw_win_tomcat_heap_config.git
#  version: 1.1/main
#- name: sra_mw_ux_tomcat_heap_config
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mw_ux_tomcat_heap_config.git
#  version: 1.1/main
#  
#- name: sra_mw_ux_apache_http_start
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mw_ux_apache_http_start.git
#  version: 1.1/main
#- name: sra_mw_ux_apache_http_stop
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mw_ux_apache_http_stop.git
#  version: 1.1/main
#- name: sra_mw_ux_apache_http_restart
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mw_ux_apache_http_restart.git
#  version: 1.1/main
#- name: sra_mw_win_apache_http_start
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mw_win_apache_http_start.git
#  version: 1.1/main
#- name: sra_mw_win_apache_http_stop
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mw_win_apache_http_stop.git
#  version: 1.1/main
#- name: sra_mw_win_apache_http_restart
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mw_win_apache_http_restart.git
#  version: 1.1/main
#- name: sra_mw_win_apache_http_check_tls
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mw_win_apache_http_check_tls.git
#  version: 1.1/main
#- name: sra_mw_ux_apache_http_check_tls
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mw_ux_apache_http_check_tls.git
#  version: 1.0/main
#  
#- name: sra_mw_win_redhat_jboss_start
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mw_win_redhat_jboss_start.git
#  version: 1.1/main
#- name: sra_mw_win_redhat_jboss_stop
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mw_win_redhat_jboss_stop.git
#  version: 1.1/main
#- name: sra_mw_ux_redhat_jboss_start
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mw_ux_redhat_jboss_start.git
#  version: 1.1/main
#- name: sra_mw_ux_redhat_jboss_stop
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mw_ux_redhat_jboss_stop.git
#  version: 1.1/main
#
#- name: sra_mw_ux_was_change_server_config
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mw_ux_was_change_server_config.git
#  version: 1.0/main
#- name: sra_mw_ux_was_download_logs
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mw_ux_was_download_logs.git
#  version: 1.0/main
#- name: sra_mw_ux_was_operational_health_chk
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mw_ux_was_operational_health_chk.git
#  version: 1.0/main
#- name: sra_mw_win_was_change_server_config
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mw_win_was_change_server_config.git
#  version: 1.0/main
#- name: sra_mw_win_was_download_logs
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mw_win_was_download_logs.git
#  version: 1.0/main
#- name: sra_mw_win_was_operational_health_chk
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mw_win_was_operational_health_chk.git
#  version: 1.0/main
#  
#- name: sra_mw_ux_websphere_start_app_server
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mw_ux_websphere_start_app_server.git
#  version: 1.2/main
#- name: sra_mw_ux_websphere_stop_app_server
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mw_ux_websphere_stop_app_server.git
#  version: 1.1/main
#- name: sra_mw_win_websphere_start_app_server
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mw_win_websphere_start_app_server.git
#  version: 1.1/main
#- name: sra_mw_win_websphere_stop_app_server
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mw_win_websphere_stop_app_server.git
#  version: 1.1/main
#
#- name: sra_mw_ux_websphere_stop_dmgr
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mw_ux_websphere_stop_dmgr.git
#  version: 1.1/main
#- name: sra_mw_ux_websphere_stop_node_agent
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mw_ux_websphere_stop_node_agent.git
#  version: 1.1/main
#- name: sra_mw_ux_websphere_start_deployment_mgr
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mw_ux_websphere_start_deployment_mgr.git
#  version: 1.1/main
#- name: sra_mw_ux_websphere_start_node_agent
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mw_ux_websphere_start_node_agent.git
#  version: 1.0/main
#- name: sra_mw_win_websphere_start_dump_head_memory
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mw_win_websphere_start_dump_head_memory.git
#  version: 1.0/main
#- name: sra_mw_ux_websphere_start_dump_head_memory
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mw_ux_websphere_start_node_agent.git
#  version: 1.0/main
#- name: sra_mw_ux_websphere_start_java_app
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mw_ux_websphere_start_java_app.git
#  version: 1.1/main
#- name: sra_mw_ux_websphere_stop_java_app
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mw_ux_websphere_stop_java_app.git
#  version: 1.1/main
#- name: sra_mw_win_websphere_start_java_app_server
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mw_win_websphere_start_java_app_server.git
#  version: 1.0/main
#- name: sra_mw_win_websphere_stop_java_app_server
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mw_win_websphere_stop_java_app_server.git
#  version: 1.0/main
#- name: sra_mw_ux_websphere_rotate_application_server_logs
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mw_ux_websphere_rotate_application_server_logs.git
#  version: 1.0/main
#- name: sra_mw_win_websphere_rotate_application_server_logs
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mw_win_websphere_rotate_application_server_logs.git
#  version: 1.0/main
#
## Middleware usecases END
#
#- name: sra_ux_oracle_rac_crs
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_ux_oracle_rac_crs.git
#  version: main
#- name: sra_ux_oracle_rac_ddbb_services
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_ux_oracle_rac_ddbb_services.git
#  version: main
#- name: sra_ux_oracle_si_ddbb_services
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_ux_oracle_si_ddbb_services.git
#  version: main
#- name: sra_ux_oracle_si_listener_services
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_ux_oracle_si_listener_services.git
#  version: main
#
#- name: sra_server_build
#  src: git+https://github.kyndryl.net/Innovate/gat_ansible_role_sra_server_build.git
#  version: v1.8.0
#  
#- name: sra_server_decom
#  src: git+https://github.kyndryl.net/Innovate/ansible_role_sra_server_decom.git
#  version: 1.8.1
#  
## New AEDEVTEAM integrations
#
#- name: sra_terraform_remote_statefile
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_terraform_remote_statefile.git
#  version: main
#
#- name: sra_mq_patch_linux
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mq_patch_linux.git
#  version: main
#
#- name: sra_mq_patch_windows
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_mq_patch_windows.git
#  version: main
#
#- name: sra_patching_linux
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_patching_linux.git
#  version: main
#
#- name: sra_patching_wsus
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_patching_wsus.git
#  version: main
#
#- name: sra_patching_windows
#  src: git+https://github.kyndryl.net/Continuous-Engineering/ansible_role_sra_patching_windows.git
#  version: main
#
