---
- name: "Call find affected host role"
  include_role: name=ansible_role_integration_findaffectedhost
  when:
  - validation_flag is defined
  - validation_flag

- name: Set affected host
  set_fact:
    affected_host: localhost
  when:
  - validation_flag is defined
  - not validation_flag

- name: Debug final_ack
  debug:
    var: final_ack

- name: Debug excludesr
  debug:
    var: excludesr

- name: Debug affected_host
  debug:
    var: affected_host

- name: Debug extra_credentials
  debug:
    var: extra_credentials

- name: Debug cred_id
  debug:
    var: cred_id

- name: Debug tower_job_template_name
  debug:
    var: tower_job_template_name

- name: Debug affected host
  debug:
    var: affected_host

- name: Debug host variables
  debug:
    var: hostvars[affected_host]


- name: "Find credentials"
  vars:
    cred_search: "{{ hostvars[hostvars['localhost']['affected_host']][item] }}"
  include_tasks: cred_finder.yml
  with_items:
    "{{  hostvars[hostvars['localhost']['affected_host']]|
         map('regex_search','.*_credential')|select('match', '^.*_credential.*')|list }}"
  when:
  - not final_ack and item is not search("next_credential")

- name: "Find extra credentials"
  vars:
    cred_search: "{{ item }}"
  include_tasks: cred_finder.yml
  with_items:
     "{{ extra_credentials }}" 
  when:
  - not final_ack and item is not search("next_credential")


- name: Debug cred_id
  debug:
    msg: "{{ cred_id | unique }}"

- name: Setting Response Body
  set_fact:
    resp_body:
      credentials: "{{ cred_id | unique }}"
      extra_vars: >-
        {
          'affected_host': {{ affected_host }},
          'sr_data': {{ sr_data |to_json }},
          'first_job_id': {{ tower_job_id }}
         }

- name: Call second job template api
  uri:
    url: "{{ lookup('env', 'TOWER_HOST') }}/api/v2/job_templates/{% if 'jt1_sra_acceptor' in tower_job_template_name %}{{ org_code }}_jt2_sra_executor++{{ org_code }}{% else %}{{ org_code }}_sra_executor_dev++{{ org_code }}{% endif %}/launch/"
#    url: "{{ lookup('env', 'TOWER_HOST') }}/api/v2/job_templates/pjl_sra_executor_dev/launch/"
#    url: "{{ lookup('env', 'TOWER_HOST') }}/api/v2/job_templates/62158/launch/"
    method: POST
    body_format: json
    headers:
      Authorization: "Bearer {{ lookup('env','TOWER_OAUTH_TOKEN') }}"
      Content-Type: application/json
    body: "{{ resp_body }}"
    status_code: 201, 200
#    status_code: 201, 200, 401
    validate_certs: false
  register: jt_launch_response
  retries: 2
  delay: 60
  until: jt_launch_response.status in [200, 201]
#  until: jt_launch_response.status in [200, 201, 401]
  when: not final_ack and not excludesr

- name: Set final ack if second job template launch failed
  set_fact:
    ticket_message: "Could not launch second job template. Error: {{ jt_launch_response.content }}"
    ticket_automation: "Escalation"
    ticket_status: "Transfer"
    ticket_automation_type: "I"
    ticket_rc: "105"
    ticket_closure_code: "Escalation - Second job template could not be launched"
    host_accessible: "NOT APPLICABLE"
    sr_allowed: "YES"
    final_ack: true
  when:
  - jt_launch_response is not skipped
  - jt_launch_response.status not in [200,201]

- name: "Send final ack to tool"
  block:
    - name: "Call final ack if final_ack is true"
      set_fact:
        tool_role: "ansible_role_integration_sra_tool_update"
      when: sr_data['TOOL_TYPE'] is defined

    - name: "[BC]Call final ack if final_ack is true"
      set_fact:
        tool_role: "ansible_role_integration_sra_snow_update"
      when: sr_data['TOOL_TYPE'] is not defined

    - name: "Execute tool role"
      include_role:
        name: "{{ tool_role }}"
      vars:
        response_message: "{{ ticket_message }}"
        comment_message: "{{ ticket_message }}"
        tool_status: "fail"
      when: tool_role == "ansible_role_integration_sra_tool_update"

    - name: "Execute tool role"
      include_role:
        name: "{{ tool_role }}"
      vars:
        worknotes: "{{ ticket_message }}"
        snow_status: "fail"
      when: tool_role == "ansible_role_integration_sra_snow_update"
  when:
    - final_ack
    - jt_launch_response is skipped or jt_launch_response.status not in [200,201]


- name: Something in block failed. Generate error.
  block:
  - name: Generate RC
    include_role:
      name: returncode
    vars:
      rc_support: account
      rc_group: misconfiguration
      rc_number: 1
      rc_message: "{{ ticket_message }}"
  when: final_ack
  rescue:
    - name: "Set exec results for unexpected failure of calling returncode role"
      debug:
        msg: "Unexpected failure in triggered returncode role"
    - meta: clear_host_errors

- name: Set Response Status
  set_fact:
    status_msg:
      EVENT_EXCLUDED: >-
        {{ 'YES' if excludesr else 'NO' }}
      HOST_FOUND: >-
        {{ 'YES' if host_status is defined and host_status.host_found else 'NO' }}
      HOST_EXCLUDED: >-
        {{ 'YES' if host_status is defined and host_status.exclude_group else 'NO' }}
      SECOND_JOB_ID: >-
        {{ jt_launch_response.json.id if(jt_launch_response is not skipped
        and (jt_launch_response.status==200 or jt_launch_response.status==201)) else 'NA' }}

- name: "Log first job results - set Custom stats"
  set_stats:
    data:
      first_jt_results: "{{ status_msg }}"
