---
- name: "Call find affected host role"
  include_role: name=ansible_role_integration_findaffectedhost
  when:
  - validation_flag is defined
  - validation_flag

- name: Set affected host
  set_fact:
    affected_host: localhost
  when:
  - validation_flag is defined
  - not validation_flag

- name: "Find credentials"
  vars:
    cred_search: "{{ hostvars[hostvars['localhost']['affected_host']][item] }}"
  include_tasks: cred_finder.yml
  with_items:
    "{{  hostvars[hostvars['localhost']['affected_host']]|
         map('regex_search','.*_credential')|select('match', '^.*_credential.*')|list }}"
  when:
  - not final_ack and item is not search("next_credential")

- name: "Find extra credentials"
  vars:
    cred_search: "{{ item }}"
  include_tasks: cred_finder.yml
  with_items:
     "{{ extra_credentials }}" 
  when:
  - not final_ack and item is not search("next_credential")


- name: Debug cred_id
  debug:
    msg: "{{ cred_id | unique }}"

- name: Setting Response Body
  set_fact:
    resp_body:
      credentials: "{{ cred_id | unique }}"
      extra_vars: >-
        {
          'affected_host': {{ affected_host }},
          'sr_data': {{ sr_data |to_json }},
          'first_job_id': {{ tower_job_id }}
         }

- name: Call second job template api
  uri:
    url: "{{ tower_host }}/api/v2/job_templates/sra_executor/launch/"
   # url: "{{ lookup('env', 'TOWER_HOST') }}/api/v2/job_templates/{% if 'jt1_sra_acceptor' in tower_job_template_name %}{{ org_code }}_jt2_sra_executor++{{ org_code }}{% else %}{{ org_code }}_sra_executor_dev++{{ org_code }}{% endif %}/launch/"
#    url: "{{ lookup('env', 'TOWER_HOST') }}/api/v2/job_templates/pjl_sra_executor_dev/launch/"
#    url: "{{ lookup('env', 'TOWER_HOST') }}/api/v2/job_templates/62158/launch/"
    method: POST
    body_format: json
    headers:
      Authorization: "Bearer {{ tower_token }}"
      Content-Type: application/json
    body: "{{ resp_body }}"
    status_code: 201, 200
#    status_code: 201, 200, 401
    validate_certs: false
  register: jt_launch_response
  retries: 2
  delay: 60
  until: jt_launch_response.status in [200, 201]
#  until: jt_launch_response.status in [200, 201, 401]
  when: not final_ack and not excludesr

- name: Set final ack if second job template launch failed
  set_fact:
    ticket_message: "Could not launch second job template. Error: {{ jt_launch_response.content }}"
    ticket_automation: "Escalation"
    ticket_status: "Transfer"
    ticket_automation_type: "I"
    ticket_rc: "105"
    ticket_closure_code: "Escalation - Second job template could not be launched"
    host_accessible: "NOT APPLICABLE"
    sr_allowed: "YES"
    final_ack: true
  when:
  - jt_launch_response is not skipped
  - jt_launch_response.status not in [200,201]

